# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test Connect' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test Connect
  pod 'Stripe'
  pod 'Alamofire', '~> 4.7'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'SwiftyJSON'
  pod 'EstimoteProximitySDK'
  pod 'EstimoteSDK'

  target 'Test ConnectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test ConnectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
